aiprojects/accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'accounts'
urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup')
]

aiprojects/aiweb/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('firstapp.urls')),
    path('firstapp/', include('firstapp.urls')),
    path('todo/', include('todoapp.urls')),
    path('accounts/', include('accounts.urls'))
]

aiprojects/todoapp/urls.py
from django.urls import path
from . import views
app_name = 'todo'
urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='add'),
    # path('list/', views.list, name='list'),
    path('list/', views.TodoList.as_view(), name='list'),
    path('update/<int:todo_id>', views.update, name='update'),
    path('delete/<int:todo_id>', views.delete, name='delete'),
    path('baseTest/', views.baseTest, name='baseTest'),
    path('question/', views.index, name='question'),
    path('question/<int:question_id>/', views.detail, name='detail'),
    path('answer/create/<int:question_id>/', views.answer_create, name='answer_create'),
    path('question/create/', views.question_create, name='question_create'),
    path('question/modify/<int:question_id>/', views.question_modify, name='question_modify'),
    path('question/delete/<int:question_id>/', views.question_delete, name='question_delete'),
]

aiprojects/common/models.py
from django.db import models

# Create your models here.

aiprojects/common/views.py
from django.shortcuts import render

# Create your views here.

aiprojects/common/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    <title>aiweb hi!</title>
</head>
<body>
<script src="{% static 'bootstrap.min.js' %}"></script>
{% include 'navbar.html' %}
{% block content %}

<script type='text/javascript'>
const delete_elements = document.getElementsByClassName("delete");
Array.from(delete_elements).forEach(function(element) {
    element.addEventListener('click', function() {
        if(confirm("정말로 삭제하시겠습니까?")) {
            location.href = this.dataset.uri;
        };
    });
});
</script>
{% endblock %}
</body>
</html>

aiprojects/common/templates/form_errors.html
{% if form.errors%}

{%for field in form%}

{%for error in field.errors%}

<div class="alert alert-danger">

    <strong>{{field.label}}</strong>

    {{error}}

 

</div>

{%endfor%}

{%endfor%}

{%for error in form.non_field_error%}

<div class="alert alert-danger">

    <strong>{{error}}</strong>

</div>

{%endfor%}

{%endif%}

aiprojects/common/templates/navbar.html
{% load static %}
<link rel="stylesheet" href="{% static 'navi.css'%}">
<nav>
  <ul>
    <li><a href="#">home</a></li>
    <li><a href="#">car</a></li>
    <li><a href="{% url 'todo:list' %}">todolist</a></li>
    <li><a href="{% url 'todo:question' %}">QnA</a></li>
    {% if user.is_authenticated %}
    <li class="right"><a href="{% url 'accounts:logout'%}" >{{user}}로그아웃</a></li>
    {% else %}
    <li class="right"><a href="{% url 'accounts:login'%}" >로그인</a></li>
    {% endif%}

  </ul>
</nav>