aiprojects/accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'accounts'
urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup')
]

aiprojects/aiweb/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('firstapp.urls')),
    path('firstapp/', include('firstapp.urls')),
    path('todo/', include('todoapp.urls')),
    path('accounts/', include('accounts.urls'))
]

aiprojects/todoapp/urls.py
from django.urls import path
from . import views
app_name = 'todo'
urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='add'),
    # path('list/', views.list, name='list'),
    path('list/', views.TodoList.as_view(), name='list'),
    path('update/<int:todo_id>', views.update, name='update'),
    path('delete/<int:todo_id>', views.delete, name='delete'),
    path('baseTest/', views.baseTest, name='baseTest'),
    path('question/', views.index, name='question'),
    path('question/<int:question_id>/', views.detail, name='detail'),
    path('answer/create/<int:question_id>/', views.answer_create, name='answer_create'),
    path('question/create/', views.question_create, name='question_create'),
    path('question/modify/<int:question_id>/', views.question_modify, name='question_modify'),
    path('question/delete/<int:question_id>/', views.question_delete, name='question_delete'),
]

aiprojects/todoapp/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class Todo(models.Model):
    todo = models.CharField(max_length=200)
    create_date = models.DateTimeField(auto_now_add=True)  # 자동 현재 시간
    end_date = models.DateTimeField(null=True, blank=True)  # 블랭크도 추가해야 값이 없어도 됨.

    author = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.todo


class Question(models.Model):
    subject = models.CharField(max_length=100)
    content = models.TextField()
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True, blank=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.subject


class Answer(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField()
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True, blank=True)

aiprojects/todoapp/forms.py
from django import forms
from .models import Question, Answer


class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question  # 사용할 모델
        fields = ['subject', 'content']
        labels = {
            'subject': '제목',
            'content': '내용',
        }

class AnswerForm(forms.ModelForm):
    class Meta:
        model = Answer
        fields = ['content']
        labels = {
            'content': '답변내용',
        }

aiprojects/todoapp/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404
from django.utils import timezone
from django.views.generic import ListView
from django.http import HttpResponseNotAllowed
from .models import Todo, Answer, Question
from .forms import QuestionForm, AnswerForm
from django.contrib import messages



def main(request):
    return render(request, 'todoapp/todo.html')


def create(request):
    # todo = request.GET.get('todo')
    # 값을 꺼내오는 로직.
    # 모델 객체로 정의한 Todo 클래스에 필요한 값을 넣어서 객체를 생성
    todo = Todo(todo=request.GET.get('todo'), author=request.user)  # create_date=timezone.now()) 얘 없어도 값이 자동으로 들어감.
    todo.save()
    # return render(request, 'todoapp/todo.html', {'todo': todo})
    return redirect('/todo/list')


# def list(request):
#     todo_list = Todo.objects.order_by('create_date')
#     return render(request,'todoapp/list.html',{'todo_list':todo_list})

class TodoList(ListView):
    model = Todo
    # template_name = 'todoapp/list.html'


def update(request, todo_id):
    todo = Todo.objects.get(id=todo_id)
    if todo.end_date:
        todo.end_date = None
    else:
        todo.end_date = timezone.now()
    todo.save()
    return redirect('/todo/list')


def delete(requset, todo_id):
    todo = Todo.objects.get(id=todo_id)
    todo.delete()
    return redirect('/todo/list')


def baseTest(request):
    return render(request, "todoapp/baseTest.html")

@login_required(login_url='accounts:login')
def answer_create(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    if request.method == "POST":
        form = AnswerForm(request.POST)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.author = request.user
            answer.create_date = timezone.now()
            answer.question = question
            answer.save()
            return redirect('todo:detail', question_id=question.id)
    else:
        return HttpResponseNotAllowed('Only POST is possible.')
    context = {'question': question, 'form': form}
    return render(request, 'todoapp/question_detail.html', context)


def index(request):
    question_list = Question.objects.order_by('-create_date')
    context = {'question_list': question_list}
    return render(request, 'todoapp/question_list.html', context)


def detail(request, question_id):
    question = Question.objects.get(id=question_id)
    context = {'question': question}
    return render(request, 'todoapp/question_detail.html', context)

@login_required(login_url='accounts:login')
def question_create(request):
    if request.method == 'POST':
        form = QuestionForm(request.POST)
        if form.is_valid():  # 폼이 유효하면
            question = form.save(commit=False)  # 임시저장 question 객체리턴
            question.author = request.user
            question.create_date = timezone.now()  # 실제저장 작성일시
            question.save()  # 데이터 저장
            return redirect('todo:index')
    else:
        form = QuestionForm()
    context = {'form': form}
    return render(request, 'todoapp/question_form.html', context)

@login_required(login_url='accounts:login')
def question_modify(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    if request.user != question.author:
        messages.error(request, '수정권한이 없습니다')
        return redirect('todo:detail', question_id=question.id)
    if request.method == "POST":
        form = QuestionForm(request.POST, instance=question)
        if form.is_valid():
            question = form.save(commit=False)
            question.modify_date = timezone.now()  # 수정일시 저장
            question.save()
            return redirect('todo:detail', question_id=question.id)
    else:
        form = QuestionForm(instance=question)
    context = {'form': form}
    return render(request, 'todoapp/question_form.html', context)

@login_required(login_url='accounts:login')
def question_delete(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    if request.user != question.author:
        messages.error(request, '삭제권한이 없습니다')
        return redirect('todo:detail', question_id=question.id)
    question.delete()
    return redirect('todo:index')

aiprojects/todoapp/templates/todoapp/baseTest.html
{% extends 'base.html' %}
{% block content %}
base Test 에서 해야할 코드들을 추가해주세요..

하하하
{% endblock %}

aiprojects/todoapp/templates/todoapp/list.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
<link rel="stylesheet" href="{% static 'todoapp/todo.css'%}">
   <div id="myDIV" class="header">
    <h2 style="margin: 5px">To Do 목록</h2>
    <input type="text" id="myInput" placeholder="할일을 적어주세요." />
    <span onclick="newElement()" class="addBtn">추가</span>
   </div>
<table id="customers">
  <tr>
    <th>번호</th>
    <th>할일</th>
    <th>작성일</th>
    <th>종료일</th>
    <th>완료</th>
    <th>삭제</th>
  </tr>
  {% for todo in todo_list%}
  <tr>
    <td>{{todo.id}}</td>
    <td>{{todo.todo}}</td>
    <td>{{todo.create_date}}</td>
    <td>{{todo.end_date |default:'진행중'}}</td>
    <td>
        {% if todo.authod_id == user.id %}
            {%if todo.end_date%}
                <a href="{% url 'todo:update' todo.id %}">완료취소</a>
            {%else%}
                <a href="{% url 'todo:update' todo.id %}">완료</a>
            {%endif%}
        {%else%}
            <a></a>
        {%endif%}
    </td>
    <td><a href="{% url 'todo:delete' todo.id %}">삭제</a></td>
  </tr>
  {%endfor%}
</table>

<script src="{% static 'todoapp/todo.js'%}"></script>
{% endblock %}

aiprojects/todoapp/templates/todoapp/question.html
<h1>{{question.subject}}</h1>
<div>
    {{question.content}}
</div>

<form action="{% url 'todo:answer_create' question.id %}" method="post">
{% csrf_token %}
<textarea name="content" id="content" row="15"></textarea>
<input type="submit" value="댓글!">
</form>

aiprojects/todoapp/templates/todoapp/question_detail.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
<div class="container my-3">
    <!-- message 표시 -->
    {% if messages %}
    <div class="alert alert-danger my-3" role="alert">
    {% for message in messages %}
        <strong>{{ message.tags }}</strong>
        <ul><li>{{ message.message }}</li></ul>
    {% endfor %}
    </div>
    {% endif %}
    <!-- 질문 -->
    <h2 class="border-bottom py-2">{{ question.subject }}</h2>
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text" style="white-space: pre-line;">{{ question.content }}</div>
            <div class="d-flex justify-content-end">
                <div class="badge bg-light text-dark p-2 text-start">
                    <div class="mb-2">{{ question.author.username }}</div>
                    <div>{{ question.create_date }}</div>
                </div>
            </div>
            <div class="my-3">
                {% if request.user == question.author %}
                <a href="{% url 'todo:question_modify' question.id  %}"
                   class="btn btn-sm btn-outline-secondary">수정</a>
                <a href="javascript:void(0)" class="delete btn btn-sm btn-outline-secondary"
                   data-uri="{% url 'todo:question_delete' question.id  %}">삭제</a>
                {% endif %}
            </div>
        </div>
    </div>
    <!-- 답변 -->
    <h5 class="border-bottom my-3 py-2">{{question.answer_set.count}}개의 답변이 있습니다.</h5>
    {% for answer in question.answer_set.all %}
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text" style="white-space: pre-line;">{{ answer.content }}</div>
            <div class="d-flex justify-content-end">
                <div class="badge bg-light text-dark p-2">
                    {{ answer.create_date }}
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
    <!-- 답변 등록 -->
    <form action="{% url 'todo:answer_create' question.id %}" method="post" class="my-3">
        {% csrf_token %}
         <!-- 오류표시 Start -->
        {% if form.errors %}
        <div class="alert alert-danger" role="alert">
            {% for field in form %}
            {% if field.errors %}
            <div>
                <strong>{{ field.label }}</strong>
                {{ field.errors }}
            </div>
            {% endif %}
            {% endfor %}
        </div>
        {% endif %}
        <!-- 오류표시 End -->
        <div class="mb-3">
            <label for="content" class="form-label">답변내용</label>
            <textarea {% if not user.is_authenticated %}disabled{% endif %}
                      name="content" id="content" class="form-control" rows="10"></textarea>
        </div>
        <input type="submit" value="답변등록" class="btn btn-primary">
    </form>
</div>
{% block script %}
<script type='text/javascript'>
const delete_elements = document.getElementsByClassName("delete");
Array.from(delete_elements).forEach(function(element) {
    element.addEventListener('click', function() {
        if(confirm("정말로 삭제하시겠습니까?")) {
            location.href = this.dataset.uri;
        };
    });
});
</script>
{% endblock %}

aiprojects/todoapp/templates/todoapp/question_form.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <h5 class="my-3 border-bottom pb-2">질문등록</h5>
    <form method="post">
        {% csrf_token %}
             <!-- 오류표시 Start -->
        {% if form.errors %}
        <div class="alert alert-danger" role="alert">
            {% for field in form %}
            {% if field.errors %}
            <div>
                <strong>{{ field.label }}</strong>
                {{ field.errors }}
            </div>
            {% endif %}
            {% endfor %}
        </div>
        {% endif %}
        <!-- 오류표시 End -->
        <div class="mb-3">
            <label for="subject" class="form-label">제목</label>
            <input type="text" class="form-control" name="subject" id="subject"
                   value="{{ form.subject.value|default_if_none:'' }}">
        </div>
        <div class="mb-3">
            <label for="content" class="form-label">내용</label>
            <textarea class="form-control" name="content"
                      id="content" rows="10">{{ form.content.value|default_if_none:'' }}</textarea>
        </div>
        <button type="submit" class="btn btn-primary">저장하기</button>
    </form>
</div>
{% endblock %}

aiprojects/todoapp/templates/todoapp/question_list.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
<div class="container my-3">
    <table class="table">
        <thead>
        <tr class="table-dark">
            <th>번호</th>
            <th>제목</th>
            <th>작성일시</th>
        </tr>
        </thead>
        <tbody>
        {% if question_list %}
        {% for question in question_list %}
        <tr>
            <td>{{ forloop.counter }}</td>
            <td>
                <a href="{% url 'todo:detail' question.id %}">{{ question.subject }}</a>
            </td>
            <td>{{ question.create_date }}</td>
        </tr>
        {% endfor %}
        {% else %}
        <tr>
            <td colspan="3">질문이 없습니다.</td>
        </tr>
        {% endif %}
        </tbody>
    </table>
    <a href="{% url 'todo:question_create' %}" class="btn btn-primary">질문을 입력해주세요.</a>
</div>
{% endblock %}

aiprojects/todoapp/templates/todoapp/todo.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>todo</title>
</head>
<body>
    <div id="myDIV" class="header">
      <h2 style="margin: 5px">To Do 목록</h2>
      <input type="text" id="myInput" placeholder="할일을 적어주세요." />
      <span onclick="newElement()" class="addBtn">추가</span>
    </div>

    <ul id="myUL">
      <li>파이썬 완성 책 완독</li>
      <li class="checked">북한산 가기</li>
      <li>자바스크립트 온라인 강의 듣기</li>
      <li>코스트코 다녀오기</li>
        <li>{{todo}}</li>
    </ul>
</body>
</html>

aiprojects/todoapp/templates/todoapp/todo_list.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
<link rel="stylesheet" href="{% static 'todoapp/todo.css'%}">
   <div id="myDIV" class="header">
    <h2 style="margin: 5px">To Do 목록</h2>
    <input type="text" id="myInput" placeholder="할일을 적어주세요." />
    {% if user.id %}
    <span onclick="newElement()" class="addBtn">추가</span>
    {%endif%}
   </div>
<table id="customers">
  <tr>
    <th>번호</th>
    <th>할일</th>
    <th>작성일</th>
    <th>종료일</th>
    <th>완료</th>
    <th>삭제</th>
  </tr>
  {% for todo in todo_list%}
  <tr>
    <td>{{todo.id}}</td>
    <td>{{todo.todo}}</td>
    <td>{{todo.create_date}}</td>
    <td>{{todo.end_date|default:"진행중..."}}</td>
    {% if user.is_authenticated %}
        {% if todo.author_id == user.id %}
        <td>
            {%if todo.end_date%}
                <a href="{% url 'todo:update' todo.id %}">완료취소</a>
            {%else%}
                <a href="{% url 'todo:update' todo.id %}">완료</a>
            {%endif%}
        </td>
        <td>
            <a href="{% url 'todo:delete' todo.id %}">삭제</a>
        </td>
        {%else%}
        <td></td>
        <td></td>
        {%endif%}
    {%else%}
        <td>
            {%if todo.end_date%}
                <a href="{% url 'accounts:signup' %}">완료취소</a>
            {%else%}
                <a href="{% url 'accounts:signup' %}">완료</a>
            </td>
            {%endif%}
            <td>
                <a href="{%url 'accounts:signup'%}">삭제</a>
            </td>
    {%endif%}
  </tr>
  {%endfor%}
</table>
<script src="{% static 'todoapp/todo.js'%}"></script>
{% endblock %}